### ISSUE TITLE
.clap binary in releases?

### ISSUE THREAD

**Issue by RustoMCSpit** [erroreyes/crrshrr#4]
https://github.com/RustoMCSpit/awesome-linux-clap-list

would like to add to the list

**Comment by erroreyes** [comment]
Oh my. Sure that would be an honor since I am not an audio developer; I'm barely learning.

**Comment by RustoMCSpit** [comment]
> Oh my. Sure that would be an honor since I am not an audio developer; I'm barely learning. I'll work on packaging the CLAP version first.

if you pack a clap tell me!!

**Comment by erroreyes** [comment]
I updated the zip file in [Releases](https://github.com/erroreyes/crrshrr/releases/tag/alpha).

**Comment by RustoMCSpit** [comment]
i see a linux .so but no linux .clap

**Comment by erroreyes** [comment]
Could you check again? This is the content of the zip file I uploaded

![image](https://github.com/erroreyes/crrshrr/assets/107824400/ef65252e-22d1-4de9-87db-4d460383f259)

where there should be two versions of the VST3 plugin for Linux and Windows, and a `crrshrr.clap` plugin that is at least Linux compatible.

**Comment by RustoMCSpit** [comment]
> Could you check again? This is the content of the zip file I uploaded
> 
> ![image](https://private-user-images.githubusercontent.com/107824400/335287422-ef65252e-22d1-4de9-87db-4d460383f259.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwOTAxMTQsIm5iZiI6MTcxNzA4OTgxNCwicGF0aCI6Ii8xMDc4MjQ0MDAvMzM1Mjg3NDIyLWVmNjUyNTJlLTIyZDEtNGRlOS04N2RiLTRkNDYwMzgzZjI1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxNzIzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzJiMWMyNGRjOGE5ZDgxOWYxMzQyNDk5NjhlMzQzMjE0NjM3YWEwZGE5ZjMwNDcyMTdlODgxNzliODFjZmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-OA2JKP_kFICgzrg4q7wXi-PlSx7aRLh5YOQcnk7EQg)
> 
> where there should be two versions of the VST3 plugin for Linux and Windows, and a `crrshrr.clap` plugin that is at least Linux compatible.

could you not make a native linux .clap?

**Comment by RustoMCSpit** [comment]
i know but can you build natively fpr linux for my list

**Comment by erroreyes** [comment]
I saw where I went wrong. I had forgotten that I had compiled for Windows right after compiling for Linux to test things. tl;dr I was totally confused, haha.

Now the release page has proper zips for Windows and Linux. Please give it a try and let me know.

**Comment by RustoMCSpit** [comment]
still broken

bitwig 5.1.9
linux mint LTS cinnamon

**Comment by erroreyes** [comment]
Could you check the Bitwig logs and if there is anything informative in there, could you share it here? I've triple checked that I am using the right binary in Kubuntu 23.10 and Bitwig v5.2 beta 3 and that it loads and runs properly.

**Comment by RustoMCSpit** [comment]
> Could you check the Bitwig logs and if there is anything informative in there, could you share it here? I've triple checked that I am using the right binary in Kubuntu 23.10 and Bitwig v5.2 beta 3 and that it loads and runs properly.

bitwig logs? wheres that?

**Comment by RustoMCSpit** [comment]
>  I've triple checked that I am using the right binary in Kubuntu 23.10 and Bitwig v5.2 beta 3 and that it loads and runs properly.

it doesnt even recognise the file. i think you uploaded a broken build

**Comment by RustoMCSpit** [comment]
also are you interested in studiorack? i made another post. if so please join the server so the dev can tell you how to implement your plugin

**Comment by erroreyes** [comment]
Here's what I did to confirm that the right binaries are compiled and uploaded:

* deleted `crrshrr.clap` from my CLAP folder `~/.clap`
* downloaded [crrshrr-LINUX.zip](https://github.com/erroreyes/crrshrr/releases/download/alpha/crrshrr-LINUX.zip) from the Releases page
* unzipped `crrshrr.clap` into my `~/.clap` directory
* opened Bitwig v5.2 beta 3
* look up `crrshrr.clap` in the browser and dragged it to an audio track
* opened UI - worked
* processed audio - worked

I repeated the steps above again, including downloading a new crrshrr-LINUX.zip file, tested it with REAPER and it also worked.

All this in Kubuntu 23.10, Bitwig v5.2 beta 3, REAPER v7.11.

____

You can find the Bitwig logs in `~/.BitwigStudio/log`. Check both the `BitwigStudio.log` and `engine.log` files to see if any issues show up for `crrshrr.clap`.

____

I saw your ticket for studiorack. I don't know what that is just yet, but let's address that in there instead of here.

**Comment by RustoMCSpit** [comment]
[2024-05-31 16:57:54.739 indexer info] Could not read metadata for crrshrr.clap com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Failed to load CLAP plug-in /home/chris/.claps/crrshrr.clap: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/chris/.claps/crrshrr.clap)

**Comment by erroreyes** [comment]
This is a clue:

```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /home/chris/.claps/crrshrr.clap)
```

At this point, this confirms that the right binaries for Linux have been uploaded, because your system does detect it correctly, and correctly detects that your system is missing dependencies needed to run the plugin, in this case the version of GLIBC in your Linux is not compatible with and probably older than what the plugin uses.

So, I'll close this ticket since the actual binaries are now correct. I would recommend that you run a system update on your Mint and see if it picks up and updates any this and any other libraries.

If you want you can open a separate ticket for this library issue to keep things organized, but again, for the issue of wrong libraries in Releases, I'll close this since it is now resolved.
